<a href="https://colab.research.google.com/github/adelolad2nd/Hamoye-Internship/blob/master/Hamoye_Internship_Stage_One_Quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HAMOYE STAGE ONE QUIZ

###Question 1

In [ ]:
A = [1,2,3,4,5,6]
B = [13, 21, 34]
A.extend(B)
print(A)

[1, 2, 3, 4, 5, 6, 13, 21, 34]


### Question 2

In [ ]:
import numpy as np
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##Preparing data set for next questions

In [ ]:
#Importing data
import numpy as np
import pandas as pd
df = pd.read_csv(r'https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv')
print(df.shape)
print(df.isnull().sum())

(29523, 11)
record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64


In [ ]:
#Filling in empty cells with most common factors
#df.groupby('fuel_unit')['fuel_unit'].count()
#df[['fuel_unit']] = df[['fuel_unit']].fillna(value = 'mcf')
#df.isnull().sum()

### Question 3

Gas

In [ ]:
df.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].mean()

fuel_type_code_pudl
coal         67.421830
gas          13.659397
nuclear    4955.157002
oil         168.877086
other        18.253856
waste        19.518122
Name: fuel_cost_per_unit_burned, dtype: float64

###Question 4

10.60 and 17.01

In [ ]:
df.describe()

utility_id_ferc1  ...  fuel_cost_per_mmbtu
count      29523.000000  ...         29523.000000
mean         118.601836  ...            19.304354
std           74.178353  ...          2091.540939
min            1.000000  ...           -41.501000
25%           55.000000  ...             1.940000
50%          122.000000  ...             4.127000
75%          176.000000  ...             7.745000
max          514.000000  ...        359278.000000

[8 rows x 7 columns]

###Question 5

15.85 and 651.37

In [ ]:
df.skew()

utility_id_ferc1                  0.605070
report_year                       0.006953
fuel_qty_burned                  15.851495
fuel_mmbtu_per_unit               4.135217
fuel_cost_per_unit_burned        19.787440
fuel_cost_per_unit_delivered    105.014227
fuel_cost_per_mmbtu             171.675535
dtype: float64

In [ ]:
df.kurtosis()

utility_id_ferc1                    1.088432
report_year                        -1.145656
fuel_qty_burned                   651.369450
fuel_mmbtu_per_unit                55.595695
fuel_cost_per_unit_burned         485.255851
fuel_cost_per_unit_delivered    11765.054226
fuel_cost_per_mmbtu             29489.132594
dtype: float64

###Question 6

In [ ]:
print(df.shape)
print(df.isnull().sum())

(29523, 11)
record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64


In [ ]:
180/29523 *100

0.609694136774718

Feature=fuel_unit, 
Total=29523, 
Percent=0.61

###Question 7

Categorical and Mode Imputation

### Question 8

fuel_quantity_burned and fuel_mmbtu_per_unit

In [ ]:
df.corr()

utility_id_ferc1  ...  fuel_cost_per_mmbtu
utility_id_ferc1                      1.000000  ...             0.006122
report_year                           0.093323  ...             0.010261
fuel_qty_burned                      -0.057447  ...            -0.001896
fuel_mmbtu_per_unit                  -0.066946  ...            -0.005884
fuel_cost_per_unit_burned            -0.037863  ...            -0.000437
fuel_cost_per_unit_delivered         -0.016414  ...            -0.000109
fuel_cost_per_mmbtu                   0.006122  ...             1.000000

[7 rows x 7 columns]

### Question 9

3.59

In [ ]:
df.groupby('report_year').first()

record_id  ...  fuel_cost_per_mmbtu
report_year                           ...                     
1994           f1_fuel_1994_12_1_0_7  ...               1.1210
1995         f1_fuel_1995_12_200_0_1  ...               1.4600
1996         f1_fuel_1996_12_204_0_1  ...               0.0000
1997           f1_fuel_1997_12_1_0_7  ...               1.1560
1998           f1_fuel_1998_12_1_0_7  ...               1.1260
1999         f1_fuel_1999_12_141_0_1  ...               1.1100
2000         f1_fuel_2000_12_141_0_1  ...               1.1290
2001         f1_fuel_2001_12_195_0_1  ...               1.1560
2002         f1_fuel_2002_12_195_0_1  ...               1.1020
2003         f1_fuel_2003_12_283_0_1  ...               2.7913
2004           f1_fuel_2004_12_1_0_7  ...               1.3490
2005         f1_fuel_2005_12_134_0_1  ...               0.7620
2006         f1_fuel_2006_12_186_0_1  ...               2.5700
2007         f1_fuel_2007_12_186_0_1  ...               3.1400
2008         f1_fuel_2008_12_122_0_1  ...               2.7160
2009         f1_fuel_2009_12_122_0_1  ...               2.4850
2010         f1_fuel_2010_12_122_0_1  ...               1.7820
2011         f1_fuel_2011_12_122_0_1  ...               2.0960
2012         f1_fuel_2012_12_122_0_1  ...               2.0740
2013         f1_fuel_2013_12_122_0_1  ...               1.9570
2014         f1_fuel_2014_12_122_0_1  ...               2.0420
2015         f1_fuel_2015_12_122_0_2  ...               9.9430
2016         f1_fuel_2016_12_122_0_2  ...               8.8070
2017         f1_fuel_2017_12_122_0_2  ...              10.2700
2018         f1_fuel_2018_12_122_0_2  ...              10.7350

[25 rows x 10 columns]

In [ ]:
(19.282-18.59)/19.282 *100

3.588839332019501

### Question 10

1997

In [ ]:
df.groupby('report_year')['fuel_cost_per_unit_delivered'].mean().sort_values()

report_year
1999       25.551627
1995       32.735269
2006       38.657484
2005       41.438184
2007       43.325023
2017       46.196861
2002       47.594361
2003       55.663493
2008       58.588197
2011       59.774667
2001       60.050396
2012       60.994502
1994       63.636060
2010       91.862105
2016      103.901761
2004      139.524275
2013      172.307591
2014      192.737183
1998      287.154420
2015      326.535511
2018      499.269966
2009      652.694163
2000      985.362877
1996     9196.705948
1997    11140.197239
Name: fuel_cost_per_unit_delivered, dtype: float64